### ISSUE TITLE
Got ws:null ERR_NAME_NOT_RESOLVED error

### ISSUE THREAD

**Issue by dexterchan** [gabrielpoca/browser-pcm-stream#12]
I download the package in my MAC 
and run node App.js

http://localhost:3700 did response.
However, the audio failed to record.... The output file is only 44 bytes.

Looking at debugger of chrome, I got following error:
WebSocket connection to 'ws://null/' failed: Error in connection establishment: net::ERR_NAME_NOT_RESOLVED

**Comment by gabrielpoca** [comment]
@dexterchan this repo is the code for [this blog post](https://subvisual.co/blog/posts/39-tutorial-html-audio-capture-streaming-to-node-js-no-browser-extensions). The APIs have changed and I'm not keeping it up to date, but you should be able to find the blog post useful.
