### ISSUE TITLE
createScriptProcessor is also deprecated

### ISSUE THREAD

**Issue by ashiitg** [gabrielpoca/browser-pcm-stream#5]
_createScriptProcessor_ is also deprecated but still continues to be supported by browsers. Request for an update with _createAudioWorker_, which shall be the replacement as per W3C editor draft (link pasted below)

http://webaudio.github.io/web-audio-api/#widl-AudioContext-createScriptProcessor-ScriptProcessorNode-unsigned-long-bufferSize-unsigned-long-numberOfInputChannels-unsigned-long-numberOfOutputChannels

**Comment by gabrielpoca** [comment]
Thank you for opening the issue 👍
