### ISSUE TITLE
Audio Quality of recorded demo file.

### ISSUE THREAD

**Issue by philkunz** [gabrielpoca/browser-pcm-stream#6]
Hi,

there are 2 major issues we notice with the default created demo2.wav file:

* Audio levels of the recording seem to be off (only low volume is undistorted) (levels on source computer are ok)
* Timing of the recording seems to be off (sounds are shifted to a higher pitch)

Are those known issues?

Thank you
Phil

**Comment by gabrielpoca** [comment]
Hi, this solution is old, I don't think it's the best approach right now. But I never had an issue with it, and it was being used in production. But if you need this you should try running a webrtc client on the server and record the audio there. I'm sorry for not being of more help.

**Comment by philkunz** [comment]
Ok, I see. We thought of it as possible alternative for getting a clear audio path, since WebRTC will not produce a perfectly untouched audio stream even if constraints for echoCancellation: false are set. I'll close the issue. Thanks for the quick response.
