### ISSUE TITLE
Does this app still work?

### ISSUE THREAD

**Issue by echezbro** [gabrielpoca/browser-pcm-stream#7]
Does this still work or need to be online (and not local) to work? I'm getting a bunch of JS errors in console, see below. Any help would be great, thanks so much!

<img width="920" alt="screen shot 2015-10-24 at 11 08 41 am" src="https://cloud.githubusercontent.com/assets/844130/10711401/a9b020b2-7a3f-11e5-9d73-a4569d0fff2f.png">

**Comment by mnokeefe** [comment]
The CDN link for binary.js is dead. Replace it with "https://cdn.jsdelivr.net/binaryjs/0.2.1/binary.min.js" in index.jade and it still works fine.

**Comment by gabrielpoca** [comment]
@echezbro I haven't run this recently, I'm not sure if it still works. I'm also not confident if this is the best solution at the moment, I haven't tried running running webrtc in the server and record the audio there. Either way, I'll look this.

**Comment by echezbro** [comment]
Thanks, Gabriel. Trying to save the audio output to a remote server, so any help is appreciated.

**Comment by gabrielpoca** [comment]
@echezbro I just tried it out, everything seems to be working fine, @mnokeefe solved it :+1:
