### ISSUE TITLE
Is it possible to make it work on Safari?

### ISSUE THREAD

**Issue by kshitizshankar** [gabrielpoca/browser-pcm-stream#9]
On safari the AudioContext doesn't work.
`"createMediaStreamSource is not a function"`

So is there any polyfill or something that can help me in making it work on Safari browser?

**Comment by gabrielpoca** [comment]
@kshitizshankar The API name can be different for Safari, I don't' remember it; you should look the docs for getUserMedia. It has been a long time since I worked with webrtc audio, I am sorry, I don't remember.

**Comment by kshitizshankar** [comment]
@gabrielpoca Yeah, it's not available in Safari.. 
(https://developer.microsoft.com/en-us/microsoft-edge/platform/catalog/spec/webaudio/)

Thanks anyways :)
